name: Testes Cypress
on: push

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # <-- Indentado corretamente
        uses: actions/checkout@v3.5.3
      - name: Cypress.io rodando testes chrome # <-- Indentado corretamente
        uses: cypress-io/github-action@v5.8.2
        with:
          command: npx cypress run --browser chrome
